# Generated by Django 5.0.6 on 2024-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_charge_type", models.CharField(max_length=20, unique=True)),
                (
                    "service_charge_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Service_Charge_percentage(%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
