# Generated by Django 5.0.6 on 2024-05-28 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_service_charge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service_charge",
            options={"verbose_name_plural": "service_charge"},
        ),
    ]
