# Generated by Django 5.0.6 on 2024-08-22 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_alter_service_charge_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service_charge",
            options={"verbose_name_plural": "Service_charge"},
        ),
    ]
