# Generated by Django 5.0.6 on 2024-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
