# Generated by Django 5.0.6 on 2024-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_restaurant_restaurant_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
