# Generated by Django 5.0.6 on 2024-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_openinghour"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openinghour",
            options={"ordering": ("day", "-from_hour")},
        ),
        migrations.AlterUniqueTogether(
            name="openinghour",
            unique_together={("restaurant", "day", "from_hour", "to_hour")},
        ),
    ]
