# Generated by Django 5.0.6 on 2024-08-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_alter_openinghour_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seating_plan_available", models.BooleanField(default=False)),
                ("tables_for_two", models.IntegerField(default=0)),
                ("tables_for_four", models.IntegerField(default=0)),
                ("tables_for_six", models.IntegerField(default=0)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_plan",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
    ]
