# Generated by Django 5.0.6 on 2024-08-27 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_seatingplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="restaurant_license",
        ),
    ]
