# Generated by Django 5.0.6 on 2024-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0008_foodhub_restaurant_food_hub"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menu_url",
            field=models.URLField(default="https://default.url"),
        ),
    ]
