# Generated by Django 5.0.6 on 2024-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_alter_fooditem_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="food_type",
            field=models.CharField(
                choices=[("veg", "Vegetarian"), ("non-veg", "Non-Vegetarian")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
