# Generated by Django 5.0.6 on 2024-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_fooditem_food_type_fooditem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="food_type",
            field=models.CharField(
                blank=True,
                choices=[("veg", "Vegetarian"), ("non-veg", "Non-Vegetarian")],
                max_length=10,
                null=True,
            ),
        ),
    ]
