# Generated by Django 5.0.6 on 2024-06-04 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="tax_data",
            new_name="service_charge_data",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_tax",
            new_name="total_charge",
        ),
    ]
