# Generated by Django 5.0.6 on 2024-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_tax_data_order_service_charge_data_and_more"),
        ("restaurant", "0005_alter_openinghour_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ManyToManyField(blank=True, to="restaurant.restaurant"),
        ),
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
