# Generated by Django 5.0.6 on 2024-07-07 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_service_charge_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="restaurant",
            new_name="restaurants",
        ),
    ]
