# Generated by Django 5.0.6 on 2024-07-18 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_restaurant_order_restaurants"),
        ("restaurant", "0005_alter_openinghour_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preorder_time",
                    models.CharField(
                        choices=[
                            ("Now", "Now"),
                            ("15min", "15 minutes"),
                            ("30min", "30 minutes"),
                            ("1 hr", "1 hr"),
                            ("1.5 hrs", "1.5 hrs"),
                            ("2 hrs", "2 hrs"),
                        ],
                        default="Now",
                        max_length=10,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
    ]
