# Generated by Django 5.0.6 on 2024-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_pendingorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingorder",
            name="preorder_time",
            field=models.CharField(
                choices=[
                    ("order-now", "order-now"),
                    ("15-mins", "15-mins"),
                    ("30-mins", "30-mins"),
                    ("45-mins", "45-mins"),
                    ("1-hr", "1-hr"),
                    ("1.5-hrs", "1.5-hrs"),
                    ("2-hrs", "2-hrs"),
                ],
                default="Now",
                max_length=10,
            ),
        ),
    ]
