# Generated by Django 5.0.6 on 2024-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_rename_created_at_pendingorder_po_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingorder",
            name="po_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
