# Generated by Django 5.0.6 on 2024-07-30 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_rename_po_id_pendingorder_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingorder",
            old_name="id",
            new_name="po_id",
        ),
    ]
