# Generated by Django 5.0.6 on 2024-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_rename_id_pendingorder_po_id"),
        ("restaurant", "0005_alter_openinghour_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurants",
            field=models.ManyToManyField(blank=True, to="restaurant.restaurant"),
        ),
    ]
