# Generated by Django 5.0.6 on 2024-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_remove_pendingorder_po_restaurants_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_restaurant_slug",
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurant_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
