# Generated by Django 5.0.6 on 2024-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_remove_pendingorder_po_restaurant_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_restaurant_data",
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurant_ids",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
