# Generated by Django 5.0.6 on 2024-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_remove_pendingorder_po_restaurant_data_and_more"),
        ("restaurant", "0005_alter_openinghour_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_restaurant_ids",
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurants",
            field=models.ManyToManyField(blank=True, to="restaurant.restaurant"),
        ),
    ]
