# Generated by Django 5.0.6 on 2024-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_pendingorder_po_total_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_onum",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
