# Generated by Django 5.0.6 on 2024-08-15 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_pendingorder_po_onum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_onum",
        ),
    ]
