# Generated by Django 5.0.6 on 2024-08-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0021_remove_pendingorder_po_onum"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_order_type",
            field=models.CharField(default="Immediate", max_length=50),
        ),
    ]
