# Generated by Django 5.0.6 on 2024-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0022_pendingorder_po_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurant_order",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
