# Generated by Django 5.0.6 on 2024-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0023_pendingorder_po_restaurant_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingorder",
            name="po_restaurant_order",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
