# Generated by Django 5.0.6 on 2024-08-17 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0024_alter_pendingorder_po_restaurant_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_restaurant_order",
        ),
    ]
