# Generated by Django 5.0.6 on 2024-08-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0026_pendingorder_po_restaurant_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurant_name",
            field=models.CharField(default="Unnamed Restaurant", max_length=50),
        ),
    ]
