# Generated by Django 5.0.6 on 2024-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0027_pendingorder_po_restaurant_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_restaurant_name",
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="po_restaurant_id",
            field=models.IntegerField(default=0),
        ),
    ]
