# Generated by Django 5.0.6 on 2024-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0028_remove_pendingorder_po_restaurant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("PayPal", "PayPal")], max_length=100),
        ),
    ]
