# Generated by Django 5.0.6 on 2024-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0029_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="num_of_people",
            field=models.FloatField(default=0),
        ),
    ]
