# Generated by Django 5.0.6 on 2024-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0030_order_num_of_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorder",
            name="po_num_of_people",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="num_of_people",
            field=models.IntegerField(default=1),
        ),
    ]
