# Generated by Django 5.0.6 on 2024-08-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0031_pendingorder_po_num_of_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="num_of_people",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="po_num_of_people",
            field=models.IntegerField(),
        ),
    ]
