# Generated by Django 5.0.6 on 2024-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0032_alter_order_num_of_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="num_of_people",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="po_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Ready", "Ready"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=15,
            ),
        ),
    ]
