# Generated by Django 5.0.6 on 2024-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0033_alter_order_num_of_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="num_of_people",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
