# Generated by Django 5.0.6 on 2024-09-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0034_alter_order_num_of_people"),
        ("restaurant", "0009_restaurant_menu_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_created_at",
        ),
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_is_ordered",
        ),
        migrations.RemoveField(
            model_name="pendingorder",
            name="po_order_number",
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="original_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_order",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="po_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="PendingOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_order_number", models.CharField(default="N/A", max_length=20)),
                ("po_is_ordered", models.BooleanField(default=False)),
                ("po_created_at", models.DateTimeField(auto_now_add=True)),
                ("po_pre_order_time", models.FloatField(default=0)),
                ("po_ordered_food_details", models.JSONField(blank=True, null=True)),
                (
                    "po_name",
                    models.CharField(default="Unnamed Pending Order", max_length=50),
                ),
                (
                    "po_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "po_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Accepted", "Accepted"),
                            ("Ready", "Ready"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="New",
                        max_length=15,
                    ),
                ),
                ("po_order_type", models.CharField(default="Immediate", max_length=50)),
                ("po_total_data", models.JSONField(blank=True, null=True)),
                ("po_restaurant_order", models.CharField(blank=True, max_length=100)),
                ("po_restaurant_id", models.IntegerField(default=0)),
                ("po_num_of_people", models.IntegerField()),
                (
                    "original_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_orders",
                        to="orders.order",
                    ),
                ),
                (
                    "po_restaurants",
                    models.ManyToManyField(blank=True, to="restaurant.restaurant"),
                ),
            ],
        ),
    ]
