# Generated by Django 5.0.6 on 2024-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0035_remove_pendingorder_po_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingOrder",
        ),
    ]
