# Generated by Django 5.0.6 on 2024-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0037_alter_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("PayPal", "Cashfree")], max_length=100),
        ),
    ]
