# Generated by Django 5.0.6 on 2024-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0038_order_transaction_id_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
