# Generated by Django 5.0.6 on 2024-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0039_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=100),
        ),
    ]
