# Generated by Django 5.0.6 on 2024-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0041_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50),
        ),
    ]
