# Generated by Django 5.0.6 on 2024-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0041_alter_payment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorders",
            name="po_seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
