# Generated by Django 5.0.6 on 2024-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0042_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingorders",
            name="po_seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
