# Generated by Django 5.0.6 on 2024-12-02 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0042_pendingorders_po_seat_number"),
        ("orders", "0043_pendingorders_po_seat_number"),
    ]

    operations = []
