# Generated by Django 5.0.6 on 2024-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0044_merge_20241202_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="seat_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
